# Site settings
title: Daniel Christodoulopoulos
name: Daniel Christodoulopoulos
description: "
  Hey 👋!! <br> I'm Daniel Christodoulopoulos and I live in Athens Greece. I 
  graduated from school of Electrical and Computer Engineering of National 
  Technical Uninversity of Athens and I am working as a Software Engineer. My 
  main interests are Computer Science and Biomedical Engineering. Currently, in 
  my spare time, I am studying Linux Kernel 💻.<br>You can check my links below
  . Feel free to contact me.
  "
url: "https://danchris.github.io"

github_username:  danchris
facebook_username: daniel.christodoulopoulos
email: danielchristodoulopoulos@gmail.com
linkedin_username: daniel-christodoulopoulos

avatar: yes
avatar_img_path: "imgs/daniel.jpg"

favicon: yes
favicon_img_path: "favicon.ico"

# Build settings
markdown: kramdown
permalink: pretty

include: [.well-known]
